[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"


[project]
name = "vna_driver"
version = "0.0.1"
authors = [
  { name="Gabriel Tomaz"},
{ name="Lincoln Machado"},
]
description = "A simple VNA driver"
requires-python = ">=3.9"
dependencies = [
    "pyserial==3.5",
]

[project.optional-dependencies]
dev = [
    "pytest"
]

[tool.hatch.build.targets.wheel]
packages=["src/vna_driver","src/vna_driver/s1p.py"]